### ISSUE TITLE
Stuck indexing when adding more than one project folder

### ISSUE THREAD

**Issue by frenchbread** [atom/fuzzy-finder#205]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Stuck indexing when adding more that one project folder to atom-beta

### Steps to Reproduce

1. `$ atom-beta ./<project>`
2. Atom opens - `Cmd+T`, Fuzzy window works fine
3. `$ atom-beta --add ~/<path>/<project>` - another project added to atom
4. In atom - `Cmd+T`, Fuzzy window shows:

![screen shot 2016-05-02 at 01 10 40](https://cloud.githubusercontent.com/assets/2122679/14944738/a15d928a-1005-11e6-8dc7-5162cd11b85a.png)

**Note!** This steps are reproducing the bug only in `atom-beta`. In `atom` this bug appears for some other reason sometimes.

**Expected behavior:** Both projects successfully indexed and possible to open file using Fuzzy window.

**Actual behavior:** Stuck while indexing

### Versions
Atom:
```
$ atom -version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Atom-beta:
```
$ atom-beta -version
Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by frenchbread** [comment]
Facing this issue not only in `Atom-beta` but in `Atom` as well

**Comment by damienstanton** [comment]
I am also having this issue. These errors are being thrown in the console:
```
Cannot find module 'atom' Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:12:19)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js:180:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:110:13)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:112:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:2:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:425:26)
    at node.js:602:27
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
and
```
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```
This only occurs on the second or more project opened. It is also happening in safe mode.

**Comment by rahatarmanahmed** [comment]
I'm able to reproduce it in Atom 1.8.0 with this:

```sh
mkdir dir1 dir2
touch dir1/file1.txt dir2/file2.txt
atom --safe dir1
atom -a dir2
```

**Comment by rahatarmanahmed** [comment]
The issue seems to be caused because the `NODE_PATH` environment variable is unset when adding a new project folder, which causes fuzzy-finder's indexing task to not be able to find the `'atom'` module.

**Comment by jacobgraf** [comment]
I am also experiencing this issue in 1.8.0. Very frustrating for sure. Hopefully it gets squashed soon!

**Comment by damienstanton** [comment]
FWIW opening a project with `cmd + shift + O` doesn't seem to internally call `atom -a` so this can be used as a temporary workaround.

**Comment by rahatarmanahmed** [comment]
The PR to fix it still hasn't been reviewed yet.

**Comment by dwelle** [comment]
This bug started to show up for me _after_ this fix landed in `1.10.beta1` -- not sure if new one or the same. Throws:

```
Cannot find module 'electron' Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at getAppVersion (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\main-process\win-shell.js:14:18)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\main-process\win-shell.js:23:12)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\main-process\win-shell.js:135:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\exports\atom.js:30:31)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\exports\atom.js:48:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:12:19)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:180:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (\Local\atom\app-1.10.0-beta1\resources\app.asar\src\task-bootstrap.js:110:13)
```

**Comment by damienstanton** [comment]
I am getting same, @dwelle. Indexing appears broken once more.

**Comment by 50Wliu** [comment]
@dwelle Can you please open a new issue?

**Comment by jacobgraf** [comment]
I had to move back to Sublime because this issue was causing me so much anxiety. I'll keep an eye on this and come back when things get sorted out. Big issue for workflow.

**Comment by maxbrunsfeld** [comment]
The fix has not yet been released; we'll do a release shortly.

**Comment by dwelle** [comment]
I'll wait for the fix to land then, before creating a new issue.

**Comment by maxbrunsfeld** [comment]
v1.9.4 is out.

**Comment by Zelgadis87** [comment]
Seems to not be working for me on Atom 1.10.0-beta3, is this expected?

**Comment by sbistrovic** [comment]
Switching back to Atom 1.9.9 from Atom beta v1.10.0-beta6 resolved the issue for me.

o_O

**Comment by Zelgadis87** [comment]
@maxbrunsfeld any news on this? Thanks!

**Comment by maxbrunsfeld** [comment]
I can't reproduce this bug on Atom v1.10.0-beta6. For those who are seeing it on that version; are there any error messages in the Developer tools?

**Comment by sbistrovic** [comment]
Cannot find module 'electron' Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at getAppVersion (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\main-process\win-shell.js:14:18)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\main-process\win-shell.js:23:12)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\main-process\win-shell.js:135:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\exports\atom.js:30:31)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\exports\atom.js:48:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:12:19)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\node_modules\fuzzy-finder\lib\load-paths-handler.js:180:4)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\task-bootstrap.js:110:13)

**Comment by sbistrovic** [comment]
C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\malim\AppData\Local\atom\app-1.10.0-beta5\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)

**Comment by sbistrovic** [comment]
This is the same error, but on different device using Atom beta 1.10.0-beta5.

**Comment by jimtahu** [comment]
I am seeing this on 1.10.0-beta6 as well (similar error messages to sbistrovic).

**Comment by maxbrunsfeld** [comment]
Thanks for [the information](https://github.com/atom/fuzzy-finder/issues/205#issuecomment-241510325) @sbistrovic. It looks like there's a second bug which is causing the same symptom.

/cc @damieng because I see `win-shell` in the stack trace.

**Comment by damieng** [comment]
This was already fixed in master, I think we need to bring win-shell.coffee over from there into the 1.10 branch.

**Comment by rwatts3** [comment]
Several releases , still seeing this in beta. Any idea what the fix could be ?

**Comment by maxbrunsfeld** [comment]
@rwatts3 Yup, this has been fixed; we'll publish the new beta version shortly.

**Comment by rwatts3** [comment]
Thank you for the hard work.  This is greatly appreciated.

**Comment by damieng** [comment]
Fix for this is checked into the 1.10-releases branch as 7c3a02a8a355a90d39c9938949d2936c2bd20cc2 and will go out in beta 7.

**Comment by maxbrunsfeld** [comment]
v1.10.0-beta7 is out.

**Comment by andrinheusser** [comment]
thanks! thanks! thanks!

**Comment by sagar2009kumar** [comment]
Hello i am getting this error


Error: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:392:9)
    at compile (C:\Users\Sagar\.atom\packages\gpp-compiler\index.js:274:31)
    at tree-view-file.treeCompile (C:\Users\Sagar\.atom\packages\gpp-compiler\index.js:251:3)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\atom-environment.js:1181:28)
    at EventEmitter.outerCallback (C:\Users\Sagar\AppData\Local\atom\app-1.13.0\resources\app.asar\src\application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by Joinyy** [comment]
I have the "Indexing project ... 0" issue on atom 1.13.0 on Win7. I am not getting any errors but fuzzy won't index any of my project folders (some local, some on network drives).
I also tested if the project size matters, but even in a folder with 2 sourcefiles, 2 headerfiles and one Makefile it stucks at zero :crying_cat_face:

**Comment by Demnogonis** [comment]
Sorry for digging this up again but I have the exact same problem.

When I first installed atom and loaded one single project directory the fuzzy search worked as intended. As soon as I set up multiple projects it stopped working and either shows "Project is empty" or "Indexing Project... 0"

The console throws these errors:

```
events.js:106 Cannot find module 'atom' Error: Cannot find module 'atom'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\node_modules\fuzzy-finder\lib\load-paths-handler.js:12:19)
    at Object.<anonymous> (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\node_modules\fuzzy-finder\lib\load-paths-handler.js:180:4)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\src\task-bootstrap.js:110:13)
    at Object.<anonymous> (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\src\task-bootstrap.js:112:4)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at [eval]:4:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:556:32)
    at bootstrap_node.js:365:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ <embedded>:70798(anonymous function) @ <embedded>:70872module.exports.Emitter.simpleDispatch @ <embedded>:63096module.exports.Emitter.emit @ <embedded>:63212(anonymous function) @ <embedded>:70824emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
events.js:106 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\Demnogonis\AppData\Local\atom\app-1.18.0\resources\app\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ <embedded>:70798(anonymous function) @ <embedded>:70872module.exports.Emitter.simpleDispatch @ <embedded>:63096module.exports.Emitter.emit @ <embedded>:63212(anonymous function) @ <embedded>:70824emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```
I'm using atom 1.18.0 on windows 10 64bit
I'm not using git. So no .gitignore file.
Also everything is local. No symlinks involved.
