### ISSUE TITLE
Atom crashes with directory loop

### ISSUE THREAD

**Issue by Arcanemagus** [atom/fuzzy-finder#306]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the directory structure of the open project has a "loop", `fuzzy-finder` will forever keep trying to reach the bottom of the tree till Atom runs out of memory and crashes. When it reloads the process starts over again.

Note that this can only happen when it can't recognize that the folder is a symlink.

### Steps to Reproduce

1. Have a network shared folder so symlink status is hidden from client.
2. Create a folder that contains a symlink to itself: `Z:\foo` containing a link `bar` that links to `Z:\foo`
3. Open this folder in Atom
4. Watch a Task spawned with [load-paths-handler.coffee](https://github.com/atom/fuzzy-finder/blob/v1.5.8/lib/load-paths-handler.coffee) use a lot of CPU, and Atom's memory continuously climb till it crashes.

**Expected behavior:**

Loop is detected or limit is hit and path searching stops.

**Actual behavior:**

Loop is never detected, path searching continues till Atom runs out of memory and crashes.

**Reproduces how often:**

100% of the time.

### Versions

Atom    : 1.19.0-beta3 x64
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS: Windows 10 Enterprise x64

### Additional Information

Killing the Task's process lets Atom work with the project folder open.

If attempted locally Atom detects that the folders are linked and stops the scan, thus accessing over a network share is necessary to hide the fact that it is a link from Atom.

**Comment by Arcanemagus** [comment]
This is somewhat related to https://github.com/atom/fuzzy-finder/issues/216 for reference, but isn't identical as it's impossible to detect that a symlink is being traversed.

**Comment by ungb** [comment]
@smashwilson do you know if this is something that might be solved with the new watcher things that you were working on?

**Comment by Arcanemagus** [comment]
Just to confirm, this is still an issue on Atom v1.25.0-beta3, although you are now required to hit <kbd>Ctrl</kbd>+<kbd>P</kbd> in order to trigger `fuzzy-finder` indexing the project.

**Comment by Arcanemagus** [comment]
Interesting new bit of information:
My home network (`samba` running on FreeBSD) seems to cap the loop 32 directories deep, showing an empty folder at the bottom most level.

The "enterprise" file system at work apparently never thought of adding that limitation, and lets you go as deep as you want till _something_ crashes.

This means that you would only be able to see the infinitely expanding memory on a system that is equally broken, otherwise you would need to hook into the internals of `fuzzy-finder` and watch the loop go till it hits the limits of whatever system you have in place.

**Comment by lee-dohm** [comment]
So it appears this was addressed on macOS and Linux by #331 but not on Windows? @Arcanemagus can you confirm?

**Comment by Arcanemagus** [comment]
I'm still seeing this on v1.34.0-nightly4 in safe mode:
![2018-10-26_11-15-48](https://user-images.githubusercontent.com/427137/47584835-965a3b00-d910-11e8-83e8-afdf0ef81a09.gif)
Note the task with constant CPU and network activity, with increasing RAM usage.
