### ISSUE TITLE
Fuzzy Finder reports "Project is empty" for non-empty project

### ISSUE THREAD

**Issue by donutmonger** [atom/fuzzy-finder#77]
I am using Atom 0.184.0 (just updated) on Mac OS X 10.10.2.

After opening Atom from the terminal in my project directory using `atom .`,  and trying to use the fuzzy finder it says that the project is empty.

![screen shot 2015-02-26 at 2 41 56 pm](https://cloud.githubusercontent.com/assets/3676616/6402577/fca00b5c-bdc5-11e4-9d43-5cf3d3e3fc35.png)

 I am only having this problem with one of my projects; opening other directories (even the parent of the buggy project) with the same command works fine, and all the files are showing in fuzzy finder.

**Comment by maxbrunsfeld** [comment]
Thanks for the report. What is the structure of this project, directory-wise? Are there any symlinks? Do you have the `Traverse Into Symlink Directories` setting enabled?

**Comment by MattKunze** [comment]
Same version/environment for me.

The project folders I'm having problems with are symlinks, though the files within the project folder are not symlinked. I'm not seeing any different behavior with or without the setting toggled, probably because it's not traversing symlinks for the search.

I am seeing different behavior in two project folders though:

project 1 - where I initially saw the issue, it was resolve launching with `atom .`, and not the search results work regardless of whether I open it in the symlinked directory or the full path

project 2 - the search results work if I open the path directly, but not in the symlink folder

somehow updating the results were *sticky* for the first project, but not the other.

I'm not seeing any errors in the JavaScript console unfortunately, and I also disabled all of my plug-ins and get the same results.

**Comment by MattKunze** [comment]
Here's a pretty easy way to reproduce the issue from a terminal:

```
matt@ghee ~/tmp $ mkdir 1
matt@ghee ~/tmp $ touch 1/test.txt
matt@ghee ~/tmp $ ln -s 1 2
matt@ghee ~/tmp $ atom 1
matt@ghee ~/tmp $ atom 2
```

The file finder shows *test.txt* when you launch atom the first time, and *Project is empty* the second time. It doesn't make a difference if the *Follow symlinks* setting is enabled

**Comment by maxbrunsfeld** [comment]
@MattKunze :+1: thanks that's really helpful.

**Comment by graygilmore** [comment]
+1 same issue for me.

**Comment by donutmonger** [comment]
@maxbrunsfeld The directory structure is quite straightforward, with no symlinks:
![screen shot 2015-02-26 at 3 15 26 pm](https://cloud.githubusercontent.com/assets/3676616/6403134/786ecdb4-bdca-11e4-9b72-14b2731a769c.png)

**Comment by maxbrunsfeld** [comment]
This will be fixed in Atom 0.185. Thanks for the report!

**Comment by donutmonger** [comment]
Awesome! Thanks for such a quick response and fix!

**Comment by viddo** [comment]
Actually I experience this same issue, but in my case I have no socket files (as the referenced commit claims is the culprit). I've managed to narrow it down to be some issue with the `.git` directory in my project dir. If I move the `.git` dir elsewhere temporarily and start atom it indexes just fine.

I've tried to both enable/disable `Traverse Into Symlink Directories`, as well as install the HEAD of this package (by cloning and using `apm link` and `apm link -d`, and starting atom w/ and w/o dev mode). "Exclude VCS Ignored Paths" is enabled ofc. 

Any other ideas on what I can/should do?

**Comment by maxbrunsfeld** [comment]
@viddo, if you disable `Exclude VCS Ignored Paths`, does indexing succeed?

**Comment by viddo** [comment]
Yes, indeed, that do the trick!

**Comment by maxbrunsfeld** [comment]
Ok, can you share the contents of your `.gitignore`?

**Comment by viddo** [comment]
https://github.com/CartoDB/cartodb/blob/master/.gitignore

**Comment by maxbrunsfeld** [comment]
@viddo I'm opening `cartodb` in Atom with the latest fuzzy-finder and `Exclude VCS Ignored Paths` enabled, and I can't reproduce this. If you clear the contents of your `.gitignore` file, does it still happen?

**Comment by viddo** [comment]
The offending line seems to be `src/`. In fact there are no directories with that name, that are not already ignored. Could that be related?

**Comment by maxbrunsfeld** [comment]
@viddo thanks for narrowing it down. Can you open a separate issue for this, if possible with the simplest possible directory structure and `.gitignore` that exhibits the problem?

**Comment by graygilmore** [comment]
I'm not sure if this needs to be reopened. I'm still experiencing this issue. Disabling `Exclude VCS Ignored Paths` fixes the issue but isn't ideal.

Structure:
![project structure](https://cloud.githubusercontent.com/assets/836758/6512191/d6dffcf4-c326-11e4-89a6-f8532384aced.png)

Special note: this folder *is* nested inside a folder that is globally ignored, though I don't imagine Atom is (or should be?) checking outside the scope of the currently loaded project. Anything I should test or post?

**Comment by maxbrunsfeld** [comment]
@graygilmore this is a separate bug; we've opened another issue for it: #79. Your special note sounds like it could be relevant. Would you mind commenting on the aforementioned issue? Thanks!

**Comment by bfagundez** [comment]
Tried with empty .gitignore (to see if was like #79) and it keeps happening, so this should be reopened IMHO. Just updated to 186, same story 3 projects.

**Comment by maxbrunsfeld** [comment]
@bfagundez this is fixed on master. See #79.

**Comment by grobmeier** [comment]
I have the "project is empty" issue with Version 1.1.0 again - no symlinks.

**Comment by mdi** [comment]
Same issue as @grobmeier above ^.

**Comment by di5abled** [comment]
Hy, same Problem here, and maybe I have another hint where this is comming from.

I have a root `Projects` folder, which contains a `.gitignore` with the contents:

```
*
!.gitignore

!.csslintrc
!.jscsrc
!.jshintrc
!.scss-lint.yml
...
```

When I open a project folder which is locted inside this folder, eg. `Projects/my-awesome-app` I finde no files in my quick search, and this is because of the `Projects/.gitignore` file. When I delete this file everything works like expected. 

Maybe you need a project *root `.gitignore`* file that settings higher up in a folder structure don't *bleed* into the current opened ones?

**Comment by foundryspatial-duncan** [comment]
I'm experiencing this issue on OSX with v1.7.2, and the cause appears to be as @di5abled describes above. This only started happening in the past few months, I think.

My project root's `.gitignore` file is fine, and the correct files are showing/hidden in the "Tree View" accordingly, however the Fuzzy Finder always says "Project is empty." If it do cmd+B to search within buffer, that appears to work.

One directory up from my project root, there's a `.gitignore` file like this:

```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```

Clearing this file makes atom work as expected. So the Tree View is honoring the project root, but the Fuzzy Finder is going too far up the directory tree.

**Comment by ReinventingHell** [comment]
@foundryspatial-duncan Yeah this is happening to me too.

**Comment by 50Wliu** [comment]
@foundryspatial-duncan @ReinventingHell your issues should have been fixed by #207.

**Comment by dolan** [comment]
I'm still seeing this happen now in plugin version 1.0.5 on Atom v1.8.0, I can't function without Ctrl+P, so I'll have to go back to vim.  I thought that the latest update would fix this.  #207 doesn't appear to have done anything, and I'm not in a symlinked directory.

**Comment by 50Wliu** [comment]
#207 has not yet been released yet.  You can install Atom 1.9.0-beta0 though which should contain the fix.

**Comment by dolan** [comment]
Thanks for clarifying. I removed my other comment so I don't confuse anyone.

**Comment by dzackgarza** [comment]
Just wanted to note that I am actually still running into this issue on atom 1.24.0 and fuzzy finder 1.7.3. Note sure if it's relevant, but I am pointing my project at a directory managed by [sparkleshare](http://www.sparkleshare.org/), which may be introducing some complexity like managing a git repo in the directory and/or making symlinks - not sure how to investigate this though, or which part might pose an issue for this package.

**Comment by 50Wliu** [comment]
@dzackgarza if you have some spare time, please feel free to open a new issue so we can investigate it further.
